
"use client";

import { useState, useEffect } from "react";
import axios from "axios";
import Link from "next/link";

interface Runbook {
  id: string;
  title: string;
  content: string;
  version: number;
  updated_at: string;
}

export default function RunbooksPage() {
  const [runbooks, setRunbooks] = useState<Runbook[]>([]);
  const [loading, setLoading] = useState(true);

  // 🚀 The Sniffer: Ensures we get the token regardless of the key name
  const getAuthToken = () => {
    if (typeof window === "undefined") return null;
    
    // Check common keys
    let token = localStorage.getItem("access") || localStorage.getItem("token") || sessionStorage.getItem("access");

    // Fallback: Scan for anything starting with 'eyJ' (JWT signature)
    if (!token) {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        const value = localStorage.getItem(key || "");
        if (value && value.startsWith("eyJ")) {
          token = value;
          break;
        }
      }
    }
    return token ? token.replace(/^["']|["']$/g, "") : null;
  };

  useEffect(() => {
    const fetchRunbooks = async () => {
      try {
        const token = getAuthToken();
        if (!token) {
          console.warn("No authentication token found.");
          setLoading(false);
          return;
        }

        const res = await axios.get("http://localhost:8000/api/runbooks/", {
          headers: { Authorization: `Bearer ${token}` }
        });
        setRunbooks(res.data);
      } catch (err) {
        console.error("Failed to fetch runbooks:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchRunbooks();
  }, []);

  return (
    <div className="min-h-screen bg-[#161722] text-gray-200 p-8 font-sans">
      <div className="max-w-6xl mx-auto">
        
        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-4">
          <div>
            <div className="text-xs font-mono text-rose-500 mb-2 uppercase tracking-widest">
              // Knowledge Base
            </div>
            <h1 className="text-4xl font-bold text-white tracking-tight">
              Runbook Registry
            </h1>
            <p className="text-gray-400 mt-2 text-sm">
              Automated operational guides generated by OPSYN Core.
            </p>
          </div>
          
          <Link href="/dashboard" className="px-5 py-2.5 bg-[#1e2030] hover:bg-gray-800 text-white rounded-lg transition-all border border-gray-700/50 flex items-center gap-2 text-sm font-semibold shadow-sm">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 text-gray-400">
              <path fillRule="evenodd" d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z" clipRule="evenodd" />
            </svg>
            Dashboard
          </Link>
        </div>

        {/* Loading State */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="h-48 bg-[#1e2030] animate-pulse rounded-xl border border-gray-700/50"></div>
            ))}
          </div>
        ) : runbooks.length === 0 ? (
          
          /* Empty State */
          <div className="text-center py-20 bg-[#1e2030] rounded-2xl border border-dashed border-gray-700/50 shadow-sm">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-12 h-12 mx-auto text-gray-600 mb-4">
              <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
            </svg>
            <p className="text-gray-400 text-lg">No runbooks found.</p>
            <p className="text-gray-500 text-sm mt-1">Resolve an incident in the chat to generate one!</p>
          </div>
          
        ) : (
          
          /* Runbooks Grid */
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {runbooks.map((rb) => (
              <div key={rb.id} className="bg-[#1e2030] border border-gray-700/50 p-6 rounded-xl hover:border-rose-500/50 hover:bg-[#25283a] transition-all group flex flex-col h-full shadow-lg">
                
                <div className="flex justify-between items-start mb-4">
                  <h3 className="text-xl font-bold text-white group-hover:text-rose-400 transition-colors line-clamp-2">
                    {rb.title}
                  </h3>
                  <span className="bg-rose-500/10 text-rose-400 text-[10px] uppercase tracking-widest px-2 py-1 rounded-md border border-rose-500/20 font-bold ml-3 shrink-0">
                    v{rb.version}
                  </span>
                </div>
                
                <p className="text-gray-400 text-sm line-clamp-3 mb-6 font-mono leading-relaxed opacity-80">
                  {rb.content.replace(/[#*`]/g, '')}
                </p>
                
                <div className="flex justify-between items-center mt-auto pt-4 border-t border-gray-700/50">
                  <span className="text-[10px] text-gray-500 font-mono uppercase tracking-widest">
                    Updated: {new Date(rb.updated_at).toLocaleDateString(undefined, { dateStyle: 'medium' })}
                  </span>
                  <Link href={`/runbooks/${rb.id}`} className="text-rose-400 hover:text-rose-300 text-sm font-bold flex items-center gap-1 transition-colors">
                    Review Doc 
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4">
                      <path fillRule="evenodd" d="M3 10a.75.75 0 01.75-.75h10.638L10.23 5.29a.75.75 0 111.04-1.08l5.5 5.25a.75.75 0 010 1.08l-5.5 5.25a.75.75 0 11-1.04-1.08l4.158-3.96H3.75A.75.75 0 013 10z" clipRule="evenodd" />
                    </svg>
                  </Link>
                </div>
                
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
